-- Jetso Console — Supabase/Postgres schema
-- Run this in the Supabase SQL editor (Project → SQL Editor → New query).
-- Safe to re-run: every statement is idempotent (IF NOT EXISTS / IF EXISTS).

-- ─── Tenants ────────────────────────────────────────────────────────────────
-- tenant_id is added now even though we're single-client, because retrofitting
-- it onto populated tables later is far more expensive (Context §3.3).
create table if not exists tenants (
    id           uuid primary key default gen_random_uuid(),
    name         text not null,
    wp_site_url  text,
    created_at   timestamptz not null default now()
);

-- Seed the single client with a fixed UUID so the backend's TENANT_ID env var
-- is known ahead of time (single-tenant MVP).
insert into tenants (id, name, wp_site_url)
values ('00000000-0000-0000-0000-000000000001', 'Reach Building', 'https://rubflo.com/')
on conflict (id) do nothing;

-- ─── Module 1: leads (already shipped) — add tenant_id ──────────────────────
alter table leads add column if not exists tenant_id uuid references tenants(id);

-- ─── Module 2: content_requests ────────────────────────────────────────────
create table if not exists content_requests (
    id             bigint generated by default as identity primary key,
    tenant_id      uuid not null references tenants(id),
    page           text not null,
    change_type    text not null,             -- 'copy' | 'style'
    summary        text not null,             -- staff's original free-text request
    before_value   text default '',
    after_value    text default '',
    status         text not null default 'drafting',
                   -- 'drafting' | 'pending_review' | 'published' | 'rejected'
    wp_post_id     integer,
    wp_preview_url text,
    submitted_by   text not null,
    created_at     timestamptz not null default now(),
    updated_at     timestamptz not null default now()
);
create index if not exists content_requests_tenant_idx
    on content_requests (tenant_id, status);

-- ─── Module 2 redesign (Context §3.3): content source + in-place PAGE edit ──
-- content_mode: 'ai_text' | 'manual_text' | 'manual_image'
alter table content_requests add column if not exists content_mode      text default 'ai_text';
alter table content_requests add column if not exists model_used        text;    -- OpenRouter model id
alter table content_requests add column if not exists wp_page_id        integer; -- the PAGE edited in place (not a new post)
alter table content_requests add column if not exists prior_content     text;    -- full raw page content for revert-on-reject
alter table content_requests add column if not exists generated_snippet text;    -- standalone copy-paste HTML/CSS
alter table content_requests add column if not exists media_id          integer; -- WP media id for manual_image
alter table content_requests add column if not exists media_url         text;
-- Soft delete ("隐藏"): rejected attempts can be hidden from the list but are
-- never hard-deleted — the request history is the audit trail.
alter table content_requests add column if not exists archived          boolean not null default false;

-- Per-user monthly AI spend cap (Context §3.6). Enforced in the backend
-- before every OpenRouter call; one row per call, summed per (user, month).
create table if not exists ai_usage (
    id          bigint generated by default as identity primary key,
    tenant_id   uuid not null references tenants(id),
    user_id     text not null,          -- who spent it
    month       text not null,          -- 'YYYY-MM'
    model       text,
    cost_usd    numeric not null default 0,
    created_at  timestamptz not null default now()
);
create index if not exists ai_usage_cap_idx on ai_usage (tenant_id, user_id, month);
alter table ai_usage enable row level security;

-- ─── Per-tenant WordPress credentials ───────────────────────────────────────
-- Not Vercel env vars (those are global). WP Application Password, never the
-- admin password (Context §3.3 / §3.4).
create table if not exists tenant_wp_credentials (
    tenant_id                uuid primary key references tenants(id),
    wp_username              text not null,
    wp_application_password  text not null,
    updated_at               timestamptz not null default now()
);

-- ─── Row Level Security ─────────────────────────────────────────────────────
-- Enabled on all four tables, defense-in-depth. The backend uses the Supabase
-- service_role key, which BYPASSES RLS — so current server behavior is
-- unchanged. RLS becomes load-bearing the moment there's a second tenant or any
-- client-side (anon-key) Supabase query (Context §3.3).
alter table tenants                enable row level security;
alter table leads                  enable row level security;
alter table content_requests       enable row level security;
alter table tenant_wp_credentials  enable row level security;

-- No permissive policies are defined for the anon/authenticated roles yet:
-- with RLS on and no policy, those roles get zero rows by default (fail-closed).
-- Add per-tenant policies here when client-side reads are introduced, e.g.:
--
--   create policy tenant_isolation on content_requests
--     for select using (tenant_id = (auth.jwt() ->> 'tenant_id')::uuid);
